# Generated by Django 4.1.1 on 2022-10-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adminagents',
            new_name='Agents',
        ),
        migrations.RenameModel(
            old_name='Adminclients',
            new_name='Clients',
        ),
        migrations.RenameModel(
            old_name='Adminoxirgi_ishlar',
            new_name='Oxirgi_ishlar',
        ),
        migrations.RenameModel(
            old_name='Adminwork',
            new_name='Work',
        ),
    ]
