# Generated by Django 4.1.1 on 2022-10-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_rename_adminagents_agents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='ismi',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agents',
            name='mulki',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='ishi',
            field=models.CharField(default=0, max_length=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='ismi',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='men_hadimda',
            field=models.CharField(default=0, max_length=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='kv',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='manzil',
            field=models.CharField(default=1, max_length=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='narx_old',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='nomi',
            field=models.CharField(default=0, max_length=33),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='rasm',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='xona1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='xona2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
