# Generated by Django 4.1.1 on 2022-10-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_agents_ismi_agents_mulki_clients_ishi_clients_ismi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='rasm',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
    ]
