# Generated by Django 4.1.1 on 2022-10-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_clients_rasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Murojaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
                ('sub', models.CharField(max_length=50)),
                ('vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='oxirgi_ishlar',
            name='sana',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
