# Generated by Django 4.1.1 on 2022-10-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_murojaat_oxirgi_ishlar_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='murojaat',
            name='mess',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
