# Generated by Django 4.1.1 on 2022-10-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0006_murojaat_mess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agents',
            old_name='ismi',
            new_name='name',
        ),
    ]
