# Generated by Django 4.1.1 on 2022-10-18 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_rename_ismi_agents_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='men_hadimda',
            new_name='men_haqimda',
        ),
    ]
