# Generated by Django 4.1.1 on 2022-10-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0008_rename_men_hadimda_clients_men_haqimda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='narx_new',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='narx_old',
            field=models.IntegerField(),
        ),
    ]
